export const SET_SIGNIN_STATUS = 'SET_SIGNIN_STATUS';
export const SET_SIMULATION = 'SET_SIMULATION';
export const SET_EXECUTIVE = 'SET_EXECUTIVE';
export const SET_AGENT = 'SET_AGENT';
export const SET_TRACKING_USER = 'SET_TRACKING_USER';